spring:
  application:
    name: entrypoint


  cloud:
    loadbalancer:
      cache:
        ttl: 60s

  activemq:
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka





server:
  port: 8080