  server:
    port: 8085

  spring:
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: entrypoint
            uri: lb://entrypoint
            predicates:
              - Path=/entrypoint/api/v1/entry-point
          - id: scenario-factory
            uri: lb://scenario-factory
            predicates:
              - Path=/scenario-factory/**
      loadbalancer:
        cache:
          ttl: 15s
    application:
      name: api-gateway