server:
  port: 8083

spring:
  application:
    name: evaluation

  activemq:
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10


  cloud:
    loadbalancer:
      cache:
        ttl: 60s

